### ISSUE TITLE
Octane not paying fees.

### ISSUE THREAD

**Issue by jdaniel96** [solana-labs/octane#13]
I have deployed octane successfully on Vercel, and when I go to the app/api I can see the fee payer and token account/mint all good!

The fee payer wallet has SOL to pay for the fees, however, when I try to send my custom token it still says: "YOU DON'T HAVE ENOUGH SOL"

Any idea why is happening?

is there a minimum of SOL that I need to hold on the account? or something else?

**Comment by jordansexton** [comment]
We don't use Github for developer support. Please ask questions on Discord, there's a #developer-support channel and a #solana-pay one where Octane comes up.
